# Generated by Django 4.0.6 on 2022-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('via', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('raw_subject', models.CharField(blank=True, max_length=612, null=True)),
                ('description', models.CharField(blank=True, max_length=1224, null=True)),
                ('priority', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('recipient', models.CharField(blank=True, max_length=1224, null=True)),
                ('requester_id', models.IntegerField(blank=True, null=True)),
                ('submitter_id', models.IntegerField(blank=True, null=True)),
                ('assignee_id', models.IntegerField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('collaborator_ids', models.CharField(blank=True, max_length=256, null=True)),
                ('follower_ids', models.CharField(blank=True, max_length=256, null=True)),
                ('email_cc_ids', models.CharField(blank=True, max_length=256, null=True)),
                ('forum_topic_id', models.IntegerField(blank=True, null=True)),
                ('problem_id', models.IntegerField(blank=True, null=True)),
                ('has_incidents', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=1224, null=True)),
                ('custom_fields', models.CharField(blank=True, max_length=1224, null=True)),
                ('satisfaction_rating', models.FloatField(blank=True, null=True)),
                ('sharing_agreement_ids', models.CharField(blank=True, max_length=1224, null=True)),
                ('fields', models.CharField(blank=True, max_length=1224, null=True)),
                ('followup_ids', models.CharField(blank=True, max_length=1224, null=True)),
                ('ticket_form_id', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('allow_channelback', models.BooleanField(default=False)),
                ('allow_attachments', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
