# Generated by Django 4.0.6 on 2022-08-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('html_body', models.TextField(blank=True, null=True)),
                ('plain_body', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('attachments', models.CharField(blank=True, max_length=512, null=True)),
                ('audit_id', models.IntegerField(blank=True, null=True)),
                ('via', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.tickets')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
