# Generated by Django 4.0.6 on 2022-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(blank=True, max_length=1224, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='raw_subject',
            field=models.TextField(blank=True, max_length=612, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='subject',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='via',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
